export const REQUEST_MOVIES = 'MOVIES/REQUEST_MOVIES';
export const FETCH_MOVIES = 'MOVIES/FETCH_MOVIES';
export const ERROR_MOVIES = 'MOVIES/ERROR_MOVIES';
export const SORT_MOVIES = 'MOVIES/SORT_MOVIES';
export const SEARCH_MOVIES = 'MOVIES/SEARCH_MOVIES';